# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 🚀 Publish

on:
  push:
    branches: 
      - master

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org
    - name: publish
    - run: npm publish
    - env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}